import numpy

a = numpy.array([10, 20, 30, 40])
b = numpy.arange(4)
c = numpy.array([[1, 0], [1, 1]])
d = numpy.arange(4).reshape(2, 2)
print(a)
print(b)
print(a - b)
print(a + b)
print(a * b)
print(b ** 2)
print(10 * numpy.sin(b))
print(a < 3)
print(c * d)
print(numpy.dot(c, d))
r = numpy.random.random((2, 4))
print(r)
print(numpy.max(r, axis=1))
